server:
  port: 8080
  servlet:
    context-path: /fkshop
spring:
  datasource:
    url: "jdbc:mysql://localhost:3360/FKShop"
    username: root
    password: 12345
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true         # Bật hỗ trợ upload file
      max-file-size: 5MB    # Kích thước tối đa cho mỗi file
      max-request-size: 5MB # Kích thước tối đa cho toàn bộ request

# secretKey
# jwt:
#  signerKey: "toM/m9xtJPF+QFijlzC6azr3XV7x9JExG8KR0gP7IU3gOf6mTqCAxve2dEWq6bQ7"
