server:
  port: 8080
  servlet:
    context-path: /fkshop
spring:
  datasource:
    url: "jdbc:mysql://localhost:3360/FKShop"
    username: root
    password: 12345
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
